twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    date:
        timezone: America/Vancouver
        format: Y-m-d g:i:s A
        interval_format: '%%d days'
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - "@NinesUtil/form/fields.html.twig"
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'jquery.collection.html.twig'
    globals:
        text_service: '@Nines\UtilBundle\Services\Text'
        comment_service: '@Nines\FeedbackBundle\Services\CommentService'
        matomo_enabled: '%dhil.matomo_enabled%'
        matomo_url: '%dhil.matomo_url%'
        matomo_siteid: '%dhil.matomo_siteid%'
        matomo_domain: '%dhil.matomo_domain%'
        title_index_authors: "%wphp.title_index_authors%"
        nines_editor_config: js/editor-config.js
        linker: '@Nines\UtilBundle\Services\EntityLinker'
