#!/bin/bash

#  ------------------------------------- 

path=${1:-"src/AppBundle"}

#  ------------------------------------- 

pwd=$(pwd)
phpcs=./vendor/bin/phpcs
outdir=web/docs
outxml=$outdir/quality.xml
outfile=$outdir/quality.html

#  ------------------------------------- 

mkdir -p $outdir

$phpcs -n \
       --standard=phpcs.xml \
       --ignore=src/AppBundle/Tests \
       --ignore=src/Nines/*/Tests \
       --report-xml=$outxml \
       --basepath=$pwd \
       $path
saxon -xsl:phpcs.xsl -s:$outxml -o:$outfile

