<?php

namespace Nines\BlogBundle\Repository;

/**
 * PostStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
