<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnRepository extends EntityRepository {

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect("MATCH (e.author, e.title) AGAINST(:q BOOLEAN) as HIDDEN score");
        $qb->orderBy('score', 'DESC');
        $qb->setParameter('q', $q);
        return $qb->getQuery();
    }

}
