<?php

namespace AppBundle\Repository;

/**
 * EnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrlandoBiblioRepository extends \Doctrine\ORM\EntityRepository
{
}
