<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsborneMarcRepository extends EntityRepository {

    /**
     * Generate a query for the index page.
     *
     * @return \Doctrine\ORM\Query
     */
    public function indexQuery() {
        $qb = $this->createQueryBuilder('m');
        $qb->where("m.field = 'ldr'");
        return $qb->getQuery();
    }

    /**
     * Do a name search for a typeahead query.
     *
     * @param string $q
     *
     * @return mixed
     */
    public function searchQuery($q) {
        $dql = <<<"ENDSQL"
SELECT e.titleId, max(MATCH (e.fieldData) AGAINST (:q BOOLEAN)) as HIDDEN score
FROM AppBundle:OsborneMarc e
WHERE MATCH (e.fieldData) AGAINST (:q BOOLEAN) > 0 AND e.field IN ('245' , '100')
group by e.titleId order by score desc
ENDSQL;
        $query = $this->_em->createQuery($dql);
        $query->setParameter('q', $q);
        return $query->execute();
    }
}
