<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Role;
use AppBundle\Entity\TitleRole;
use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{

    /**
     * Do a name search for a typeahead query.
     *
     * @param string $q
     *
     * @return mixed
     */
    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere("e.name LIKE :q");
        $qb->orderBy('e.name');
        $qb->setParameter('q', "{$q}%");
        return $qb->getQuery()->execute();
    }

    /**
     * Count the titles in a given role.
     *
     * @param Role $role
     *
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countTitles(Role $role) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(1)');
        $qb->andWhere('titlerole.role = :role');
        $qb->setParameter('role', $role);
        $qb->from(TitleRole::class, 'titlerole');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
