<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Source;
use AppBundle\Entity\Title;
use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends EntityRepository
{

    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere("e.name LIKE :q");
        $qb->orderBy('e.name');
        $qb->setParameter('q', "{$q}%");
        return $qb->getQuery()->execute();
    }

    public function countTitles(Source $source) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(title.id)');
        $qb->andWhere('title.source = :source');
        $qb->setParameter('source', $source);
        $qb->from(Title::class, 'title');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
