<?php

declare(strict_types=1);

/*
 * (c) 2021 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\Repository;

use App\Entity\Genre;
use App\Entity\Title;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\Query;
use Doctrine\Persistence\ManagerRegistry;
use Nines\UserBundle\Entity\User;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends ServiceEntityRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Genre::class);
    }

    public function indexQuery() : Query {
        $qb = $this->createQueryBuilder('e');
        $qb->orderBy('e.name');

        return $qb->getQuery();
    }

    public function titlesQuery(Genre $genre, ?User $user) : Query {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t');
        $qb->from(Title::class, 't');
        $qb->where(':genre MEMBER OF t.genres');
        $qb->setParameter('genre', $genre);
        if ( ! $user) {
            $qb->andWhere('(t.finalcheck = 1) OR (t.finalattempt = 1)');
        }
        $qb->orderBy('t.title');

        return $qb->getQuery();
    }

    /**
     * Execute a name search for a typeahead widget.
     *
     * @return mixed
     */
    public function typeaheadQuery(string $q) {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere('e.name LIKE :q');
        $qb->orderBy('e.name');
        $qb->setParameter('q', "{$q}%");

        return $qb->getQuery()->execute();
    }

    /**
     * Count the titles in a genre.
     *
     * @param ?User $user
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     *
     * @return mixed
     */
    public function countTitles(Genre $genre, ?User $user = null) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(title.id)');
        $qb->andWhere(':genre MEMBER OF title.genres');
        if ( ! $user) {
            $qb->andWhere('title.finalattempt = 1 OR title.finalcheck = 1');
        }
        $qb->setParameter('genre', $genre);
        $qb->from(Title::class, 'title');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
