<?php

namespace App\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * JacksonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JacksonRepository extends ServiceEntityRepository {
    /**
     * Do a name search on author and title for a typeahead query.
     *
     * @param string $q
     *
     * @return mixed
     */
    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect('MATCH (e.author, e.title) AGAINST(:q BOOLEAN) as HIDDEN score');
        $qb->where('MATCH (e.author, e.title) AGAINST(:q BOOLEAN) > 0');
        $qb->orderBy('score', 'DESC');
        $qb->setParameter('q', $q);

        return $qb->getQuery();
    }
}
