<?php

namespace App\Repository;

/**
 * EnRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcTagStructureRepository extends \Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository {
}
