<?php

namespace App\Repository;

/**
 * TitleSourceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitleSourceRepository extends \Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository {
}
