<?php

declare(strict_types=1);

namespace App\Tests\Repository;

use App\Repository\PageRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class PageRepositoryTest extends ServiceTestCase {
    private ?PageRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(PageRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(2, $this->repo->indexQuery()->execute());
    }

    public function testIndexQueryIncludePrivate() : void {
        $this->assertCount(5, $this->repo->indexQuery(true)->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(2, $this->repo->searchQuery('paragraph')->execute());
    }

    public function testSearchQueryIncludePrivate() : void {
        $this->assertCount(5, $this->repo->searchQuery('paragraph', true)->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = self::getContainer()->get(PageRepository::class);
    }
}
