<?php

declare(strict_types=1);

namespace App\Tests\Repository;

use App\Repository\PostStatusRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class PostStatusRepositoryTest extends ServiceTestCase {
    private ?PostStatusRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(PostStatusRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(5, $this->repo->indexQuery()->execute());
    }

    public function testTypeaheadQuery() : void {
        $this->assertCount(1, $this->repo->typeaheadQuery('label 1')->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(1, $this->repo->searchQuery('"label 1"')->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = self::getContainer()->get(PostStatusRepository::class);
    }
}
