<?php

namespace FeedbackBundle\Repository;

/**
 * CommentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
