nines_blog:
  resource: '@NinesBlogBundle/config/routes.yaml'

nines_editor:
  resource: '@NinesEditorBundle/config/routes.yaml'
  prefix: editor

nines_feedback:
  prefix: /feedback
  resource: '@NinesFeedbackBundle/config/routes.yaml'

nines_user:
  resource: '@NinesUserBundle/config/routes.yaml'
